# Adaptive RAG 配置文件 - 基于 FlexRAG

# 助手配置
assistant:
  name: adaptive
  model_name: "openai/gpt-4"
  max_tokens: 2048
  temperature: 0.1

# 查询分析配置
query_analysis:
  enable_query_decomposition: true
  max_decomposition_depth: 3
  decomposition_threshold: 50  # token 数量阈值
  llm_model: "openai/gpt-3.5-turbo"

# 策略路由配置
strategy_routing:
  enable_dynamic_routing: true
  default_keyword_weight: 0.3
  default_vector_weight: 0.7

# 混合检索配置
hybrid_retrieval:
  enable_hybrid_retrieval: true
  max_retrieved_docs: 20
  final_docs_count: 5
  
  # 检索器配置
  keyword_retriever:
    type: "bm25"
    index_path: "./data/keyword_index"
  
  vector_retriever:
    type: "dense"
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    index_path: "./data/vector_index"

# 聚合配置
aggregation:
  relevance_weight: 0.7
  diversity_weight: 0.3
  redundancy_threshold: 0.85

# 重排序配置
reranking:
  enabled: true
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  top_k: 10

# 数据配置
data:
  corpus_path: "./data/corpus"
  index_path: "./data/index"
  
# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
